nginx: 
    build: ./nginx
    ports: 
        - 80:80
    links: 
        - tomcat

tomcat: 
    build: ./tomcat
    links: 
        - mysql
        - redis

mysql: 
    build: ./mysql
    environment: 
        MYSQL_ROOT_PASSWORD: 123456

redis: 
    build: ./redis