version: '2'

services: 
  nginx: 
    image: nginx:1.11
    ports: 
      - 80:80
    links: 
     - tomcat
    volumes: 
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: HttpProxy
  
  tomcat: 
    image: tomcat:8.0
    links: 
      - mysql
      - redis
    volumes: 
      - $PWD/tomcat/webapps/:/etc/local/tomcat/webapps/
    container_name: WebServer
  
  mysql: 
    image: mysql:5.7
    ports: 
      - 8689:3306
    volumes: 
      - /data/mysql/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    container_name: DB
  
  redis: 
     image: redis:3.2
     ports: 
       - 8789:6379
     container_name: MemoryDB
